version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: helloworld Build and push Docker image
          command: |
            sudo docker build -t cloudplexng/helloworld:${CIRCLE_BUILD_NUM} .
            sudo docker login -u "$username" -p "$password"
            sudo docker push cloudplexng/helloworld:${CIRCLE_BUILD_NUM}
            curl --request POST -H "Content-Type: application/json" -H "token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.CnsKICAidGVhbXNfcm9sZXMiOnt9LAogICJpc3MiOiJjbG91ZHBsZXgiLAogICJleHAiOiIwIiwKICAidXNlcm5hbWUiOiJoYXNlZWJAY2xvdWRwbGV4LmlvIiwKICAiY29tcGFueUlkIjoiNWRhYWM0ZGY2YTllMmYwMDFjN2Q4M2IwIiwKICAiaXNBZG1pbiI6ImZhbHNlIiwKICAidG9rZW5fdHlwZSI6IjEiLAogICJteXJvbGVzIjpbIlN1cGVyLVVzZXIiXQp9CiAgICAgIA.Xx6x2kfL566VBWneB4IU_FDo4qxb8ab9O21lkKmV2n0" --data '{"image":"cloudplexng/helloworld","tag": "'"${CIRCLE_BUILD_NUM}"'" , "type":"container", "project_ids":["project-helloworld-4"]}' https://app.cloudplex.io/rabbit/api/v1/cd/trigger/deployment