version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: helloworld Build and push Docker image
          command: |
            sudo docker build -t haseebh/helloworld:${CIRCLE_BUILD_NUM} .
            sudo docker login -u "$username" -p "$password"
            sudo docker push haseebh/helloworld:${CIRCLE_BUILD_NUM}
